FROM nvidia/cuda:9.2-cudnn7-devel-ubuntu18.04
LABEL maintainer "paul-emmanuel@outlook.com"

# Install all dependencies for OpenCV 3.4
RUN echo "deb http://security.ubuntu.com/ubuntu xenial-security main" | tee -a /etc/apt/sources.list && apt-get -y update \
    && apt-get -y install python3 python-dev python3-dev wget unzip \
    build-essential cmake git pkg-config  libssl-dev libffi-dev \
    libxml2-dev libxslt1-dev zlib1g-dev libatlas-base-dev gfortran \
    libjasper-dev libgtk2.0-dev libavcodec-dev libavformat-dev \
    libswscale-dev libjpeg-dev libpng-dev libtiff-dev libv4l-dev

RUN wget https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py && pip3 install numpy && rm get-pip.py \
    && wget https://github.com/Itseez/opencv/archive/3.4.0.zip -O opencv3.zip \
    && unzip -q opencv3.zip && mv /opencv-3.4.0 /opencv && rm opencv3.zip \
    && wget https://github.com/Itseez/opencv_contrib/archive/3.4.0.zip -O opencv_contrib3.zip \
    && unzip -q opencv_contrib3.zip && mv /opencv_contrib-3.4.0 /opencv_contrib && rm opencv_contrib3.zip \
    && mkdir /opencv/build && cd /opencv/build \
    && cmake -D CMAKE_BUILD_TYPE=RCUDAELEASE \
      -D BUILD_PYTHON_SUPPORT=ON \
      -D CMAKE_INSTALL_PREFIX=/usr/local \
      -D OPENCV_EXTRA_MODULES_PATH=/opencv_contrib/modules \
      -D BUILD_EXAMPLES=OFF \
      -D PYTHON_DEFAULT_EXECUTABLE=/usr/bin/python3 \
      -D BUILD_opencv_python3=ON \
      -D BUILD_opencv_python2=OFF \
      -D WITH_IPP=OFF \
      -D WITH_FFMPEG=ON \
      -D WITH_V4L=ON .. \
    && cd /opencv/build && make -j$(nproc) && make install && ldconfig \
    && apt-get clean

# Install ffmpeg runtime
RUN apt-get -y -qq update && apt-get -y install ffmpeg

# Define default command.
CMD ["python3"]
